# Generated by Django 4.2.3 on 2023-08-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblogs', '0002_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
